const $=id=>document.getElementById(id);let apiKey=sessionStorage.getItem("uiip-dashboard-key")||"";
function esc(value){const node=document.createElement("span");node.textContent=String(value??"");return node.innerHTML}
async function request(path){const response=await fetch(path,{headers:{"X-API-Key":apiKey,"Accept":"application/json"}});if(!response.ok){const body=await response.json().catch(()=>({}));const error=new Error(body.error?.message||`Request failed (${response.status})`);error.status=response.status;throw error}return response.json()}
async function optional(path){try{return await request(path)}catch(error){if(error.status===404)return null;throw error}}
function money(value,currency){return new Intl.NumberFormat(undefined,{style:"currency",currency,maximumFractionDigits:2}).format(Number(value))}
function number(value,maximum=6){return new Intl.NumberFormat(undefined,{maximumFractionDigits:maximum}).format(Number(value))}
function signedMoney(value,currency){const amount=Number(value);return `${amount>0?"+":""}${money(amount,currency)}`}
function renderEvents(items){$("events").innerHTML=items.length?items.map(item=>`<div class="event"><div class="event-head"><strong>${esc(item.event_type)}</strong><time>${esc(new Date(item.occurred_at).toLocaleString())}</time></div><code>${esc(item.correlation_id)}</code></div>`).join(""):`<div class="empty">No operational events recorded yet.</div>`}
function renderMetrics(items){$("metrics").innerHTML=items.length?items.map(item=>`<div class="metric"><strong>${esc(item.labels.method||item.name)}</strong><span>Status ${esc(item.labels.status||"—")}</span><b>${esc(item.value)}</b></div>`).join(""):`<div class="empty">No request metrics recorded yet.</div>`}
function renderPortfolio(snapshot,history){if(!snapshot){$("portfolio-status").textContent="Empty";$("portfolio-empty").hidden=false;$("portfolio-data").hidden=true;$("portfolio-meta").textContent="No persisted snapshot";$("portfolio-fingerprint").textContent="";return}const currency=snapshot.currency;const market=Number(snapshot.total_market_value);const cost=Number(snapshot.total_cost_basis);const gain=market-cost;const gainPct=cost?gain/cost*100:0;const stale=Date.now()-new Date(snapshot.as_of).getTime()>7*24*60*60*1000;$("portfolio-status").textContent=stale?"Stale":"Ready";$("portfolio-empty").hidden=true;$("portfolio-data").hidden=false;$("portfolio-meta").textContent=`As of ${new Date(snapshot.as_of).toLocaleString()}${stale?" · older than 7 days":""}`;$("portfolio-fingerprint").textContent=`${snapshot.fingerprint.slice(0,12)}…`;$("portfolio-market").textContent=money(market,currency);$("portfolio-cost").textContent=money(cost,currency);$("portfolio-gain").textContent=signedMoney(gain,currency);$("portfolio-gain").className=gain>=0?"positive":"negative";$("portfolio-return").textContent=`${gain>=0?"+":""}${gainPct.toFixed(2)}%`;$("portfolio-return").className=gain>=0?"positive":"negative";$("portfolio-count").textContent=number(snapshot.position_count,0);const groups={};for(const item of snapshot.positions)groups[item.portfolio_group]=(groups[item.portfolio_group]||0)+Number(item.market_value);$("portfolio-allocation").innerHTML=Object.entries(groups).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([group,value])=>{const pct=market?value/market*100:0;return `<div class="allocation-row"><strong>${esc(group.toUpperCase())}</strong><div class="bar"><i style="width:${Math.max(0,Math.min(100,pct)).toFixed(2)}%"></i></div><span>${esc(pct.toFixed(1))}%</span></div>`}).join("");$("portfolio-positions").innerHTML=snapshot.positions.map(item=>{const itemGain=Number(item.market_value)-Number(item.cost_basis);return `<tr><td><span class="position-name"><strong>${esc(item.name||item.symbol||item.asset_id)}</strong><small>${esc(item.symbol||item.asset_id)}</small></span></td><td>${esc(item.portfolio_group.toUpperCase())}</td><td>${esc(number(item.quantity))}</td><td>${esc(money(item.cost_basis,item.currency))}</td><td>${esc(money(item.market_value,item.currency))}</td><td class="${itemGain>=0?"positive":"negative"}">${esc(signedMoney(itemGain,item.currency))}</td></tr>`}).join("");$("portfolio-history").innerHTML=history.length?history.map(item=>`<div class="history-row"><strong>${esc(new Date(item.as_of).toLocaleDateString())}</strong><span>${esc(money(item.total_market_value,item.currency))} · ${esc(item.position_count)} positions</span></div>`).join(""):`<div class="empty">No earlier snapshots.</div>`}
async function load(){if(!apiKey){$("content").hidden=true;$("message").textContent="Waiting for authentication.";return}$("message").className="message";$("message").textContent="Loading operational data and portfolio snapshot…";try{const [summary,events,metrics,portfolio,history]=await Promise.all([request("/v1/dashboard/summary"),request("/v1/dashboard/events?limit=50"),request("/v1/dashboard/metrics"),optional("/v1/portfolio/snapshots/current"),optional("/v1/portfolio/snapshots?limit=10")]);$("content").hidden=false;$("auth").hidden=true;$("message").textContent="";const healthy=summary.service.live&&summary.service.ready;$("status-dot").className=`dot ${healthy?"good":"bad"}`;$("service-status").textContent=healthy?"Service ready":"Service requires attention";$("updated").textContent=`Updated ${new Date(summary.generated_at).toLocaleTimeString()}`;$("request-count").textContent=summary.activity.api_requests.toLocaleString();$("event-count").textContent=summary.activity.recorded_events.toLocaleString();$("provider-status").textContent=summary.integrations.alpha_vantage&&summary.integrations.fred?"2 / 2":"Review";renderPortfolio(portfolio,history?.items||[]);renderEvents(events.items);renderMetrics(metrics.counters)}catch(error){$("content").hidden=true;$("auth").hidden=false;$("message").className="message error";$("message").textContent=error.message;sessionStorage.removeItem("uiip-dashboard-key")}}
$("auth-form").addEventListener("submit",event=>{event.preventDefault();apiKey=$("api-key").value.trim();sessionStorage.setItem("uiip-dashboard-key",apiKey);$("api-key").value="";load()});$("refresh").addEventListener("click",load);load();
