(()=>{
"use strict";
const RECORD_TYPE="tactical_state";
const DOMAIN="metals";
const NO_OVERLAY_COPY="No tactical overlay means the frozen directional regime conditions are not currently satisfied; it is not a negative long-term thesis, sell signal, zero expected return, or allocation instruction.";
const UNRESOLVED_COPY="Unsupported fields remain unavailable rather than being synthesized from semantically different evidence.";
const COMMODITY_TACTICAL_COPY="Vehicle-level tactical context is not applicable to commodity thesis records. UIP does not synthesize vehicle momentum, drawdown, or tactical state for commodities.";
let pendingDetail=null;
function clean(value){return String(value??"").replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase())}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function fmtPct(value){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:String(value)}
function fmtNumber(value,digits=2){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):String(value)}
function fmtMoney(value){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n):String(value)}
function rows(detail,type){return Array.isArray(detail?.records?.[type])?detail.records[type]:[]}
function payloads(detail,type){return rows(detail,type).map(record=>record.payload||{})}
function firstTactical(detail){const tactical=rows(detail,RECORD_TYPE);return tactical.length?tactical[0].payload||null:null}
function uncertaintyRows(detail){return payloads(detail,"metals_uncertainty_adjusted").slice().sort((a,b)=>Number(a.horizon_months)-Number(b.horizon_months))}
function bestUncertainty(detail){const values=uncertaintyRows(detail);return values.length?values[values.length-1]:null}
function recommendationChange(detail){return payloads(detail,"metals_recommendation_change")[0]||null}
function modelComponents(detail){return payloads(detail,"metals_model_component").slice().sort((a,b)=>Number(a.horizon_months)-Number(b.horizon_months)||String(a.model_name||"").localeCompare(String(b.model_name||"")))}
function regimeProbabilities(detail){return payloads(detail,"metals_regime_probability").slice().sort((a,b)=>Number(b.probability)-Number(a.probability))}
function currentPrice(detail){return payloads(detail,"metals_current_price")[0]||null}
function priceHistory(detail){return payloads(detail,"metals_price_history").slice().sort((a,b)=>String(a.observation_date||"").localeCompare(String(b.observation_date||"")))}
function detailAssetId(detail){if(detail?.asset_id)return String(detail.asset_id);for(const type of ["recommendation","asset","forecast","metals_model_component","metals_current_price","metals_uncertainty_adjusted",RECORD_TYPE]){for(const row of payloads(detail,type)){const value=row.universal_asset_id??row.asset_id??row.universal_vehicle_id;if(value)return String(value)}}return ""}
function isCommodityDetail(detail){return detailAssetId(detail).startsWith("metals:commodity:")||(!firstTactical(detail)&&modelComponents(detail).length>0)}
function tacticalLabel(payload,commodity=false){if(commodity)return "Vehicle-level tactical context not applicable";if(!payload)return "Tactical state unavailable";if(payload.tactical_state==="TACTICAL_SUPPORTIVE")return "Tactical supportive";if(payload.tactical_state==="TACTICAL_DEFENSIVE")return "Tactical defensive";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return "No tactical overlay";return "Tactical state unavailable"}
function tacticalExplanation(payload,commodity=false){if(commodity)return COMMODITY_TACTICAL_COPY;if(!payload)return "No certified tactical-state record is available for this vehicle.";if(payload.is_reference_control===true)return "Reference/control vehicle; not an opportunity recommendation.";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return NO_OVERLAY_COPY;return `Current bounded tactical interpretation: ${clean(payload.tactical_state)}. This does not replace the certified long-term recommendation, forecast, risk evidence, or execution controls.`}
function tacticalViewModel(detail){const payload=firstTactical(detail);const commodity=isCommodityDetail(detail);return {recordType:RECORD_TYPE,domain:DOMAIN,label:tacticalLabel(payload,commodity),explanation:tacticalExplanation(payload,commodity),commodity,asOf:payload?.as_of_date??null,regime:payload?.candidate_regime??null,stateReason:payload?.state_reason??null,isReferenceControl:payload?.is_reference_control===true,available:payload?.state_available===true,return1m:payload?.return_1m_pct??null,return3m:payload?.return_3m_pct??null,return6m:payload?.return_6m_pct??null,distanceMa50:payload?.distance_ma50_pct??null,distanceMa200:payload?.distance_ma200_pct??null,drawdown:payload?.current_drawdown_pct??null,volatility3m:payload?.realized_volatility_3m_pct??null};}
function uncertaintyTable(detail){const values=uncertaintyRows(detail);if(!values.length)return "";return `<section class="metals-evidence-block metals-forecast-return-context"><h5>Forecast return context</h5><p class="governance-note">Raw and uncertainty-adjusted expected returns are certified vehicle evidence. Penalties are model adjustments, not forecast bounds or generic risk scores.</p><div class="rec-detail-table"><table><thead><tr><th>Horizon</th><th>Raw expected return</th><th>Adjusted expected return</th><th>Uncertainty penalty</th><th>Downside penalty</th></tr></thead><tbody>${values.map(row=>`<tr><td>${fmtNumber(row.horizon_months,0)} mo</td><td>${fmtPct(Number(row.raw_expected_return)*100)}</td><td>${fmtPct(Number(row.adjusted_expected_return)*100)}</td><td>${fmtPct(Number(row.uncertainty_penalty)*100)}</td><td>${fmtPct(Number(row.downside_penalty)*100)}</td></tr>`).join("")}</tbody></table></div></section>`}
function recommendationChangeBlock(detail){const value=recommendationChange(detail);if(!value)return "";return `<section class="metals-evidence-block"><h5>Recommendation evidence</h5><div class="metals-tactical-metrics"><div><span>Previous action</span><strong>${clean(value.previous_action??"unavailable")}</strong></div><div><span>Current action</span><strong>${clean(value.current_action??"unavailable")}</strong></div><div><span>Previous confidence</span><strong>${fmtNumber(value.previous_confidence)}</strong></div><div><span>Current confidence</span><strong>${fmtNumber(value.current_confidence)}</strong></div></div><p class="governance-note">${escapeHtml(value.explanation??"No recommendation-change explanation is populated.")}</p></section>`}
function commodityModelBlock(detail){const models=modelComponents(detail);if(!models.length)return "";return `<section class="metals-evidence-block"><h5>Commodity model components</h5><p class="governance-note">Certified component forecasts are shown with their source model weights. They are not synthesized into unsupported price bounds.</p><div class="rec-detail-table"><table><thead><tr><th>Horizon</th><th>Model</th><th>Model forecast</th><th>Weight</th></tr></thead><tbody>${models.map(row=>`<tr><td>${fmtNumber(row.horizon_months,0)} mo</td><td>${clean(row.model_name??"unavailable")}</td><td>${fmtNumber(row.model_forecast,4)}</td><td>${fmtPct(Number(row.model_weight)*100)}</td></tr>`).join("")}</tbody></table></div></section>`}
function commodityRegimeBlock(detail){const regimes=regimeProbabilities(detail);if(!regimes.length)return "";return `<section class="metals-evidence-block"><h5>Commodity regime probabilities</h5><div class="metals-tactical-metrics">${regimes.map(row=>`<div><span>${clean(row.regime??"regime")}</span><strong>${fmtPct(Number(row.probability)*100)}</strong></div>`).join("")}</div><p class="governance-note">These are long-term forecast-regime probabilities, not the vehicle tactical classifier.</p></section>`}
function renderTacticalPanel(detail){pendingDetail=detail;const vm=tacticalViewModel(detail);const asOf=vm.asOf?`<span>As of ${vm.asOf}</span>`:vm.commodity?"<span>Vehicle tactical as-of: not applicable</span>":"<span>As-of date unavailable</span>";const regime=vm.regime?`<span>Regime: ${clean(vm.regime)}</span>`:"";const reason=vm.stateReason?`<small>${clean(vm.stateReason)}</small>`:"";const metrics=vm.commodity?"":`<div class="metals-tactical-metrics"><div><span>1M momentum</span><strong>${fmtPct(vm.return1m)}</strong></div><div><span>3M momentum</span><strong>${fmtPct(vm.return3m)}</strong></div><div><span>6M momentum</span><strong>${fmtPct(vm.return6m)}</strong></div><div><span>Current drawdown</span><strong>${fmtPct(vm.drawdown)}</strong></div><div><span>vs MA50</span><strong>${fmtPct(vm.distanceMa50)}</strong></div><div><span>vs MA200</span><strong>${fmtPct(vm.distanceMa200)}</strong></div><div><span>3M volatility</span><strong>${fmtPct(vm.volatility3m)}</strong></div></div>`;const evidence=vm.commodity?`${commodityRegimeBlock(detail)}${commodityModelBlock(detail)}`:`${recommendationChangeBlock(detail)}`;queueMicrotask(()=>enhanceResearchDetail(detail));return `<aside class="rec-tactical-panel metals-tactical-rich ${vm.commodity?"metals-tactical-na":""}" data-record-type="${RECORD_TYPE}"><span class="eyebrow">${vm.commodity?"SUPPORTING CONTEXT":"TACTICAL & SUPPORTING CONTEXT"}</span><h4>${vm.label}</h4><p>${vm.explanation}</p><div class="rec-tactical-meta">${asOf}${regime}</div>${metrics}${reason}${evidence}<p class="governance-note">${UNRESOLVED_COPY}</p></aside>`;}
async function detailRequest(assetId){const key=sessionStorage.getItem("uiip-dashboard-key")||"";if(!key)return null;const response=await fetch(`/v1/presentation/assets/${encodeURIComponent(DOMAIN)}/${encodeURIComponent(assetId)}`,{headers:{"X-API-Key":key,"Accept":"application/json"}});if(!response.ok)return null;return response.json()}
function findKpi(root,label){return [...root.querySelectorAll(".metals-kpi,.metals-hero-metric")].find(node=>node.querySelector("span")?.textContent?.trim()===label)||null}
function setCardForecast(card,detail){const target=findKpi(card,"Forecast return")||findKpi(card,"Adjusted return")||findKpi(card,"Governed return");if(!target)return;const label=target.querySelector("span");const strong=target.querySelector("strong");if(!strong)return;const best=bestUncertainty(detail);if(best){if(label)label.textContent="Adjusted return";strong.textContent=fmtPct(Number(best.adjusted_expected_return)*100);strong.title=`${fmtNumber(best.horizon_months,0)}-month uncertainty-adjusted expected return; raw expected return ${fmtPct(Number(best.raw_expected_return)*100)}`;target.dataset.evidenceSource="metals_uncertainty_adjusted";return}const forecasts=payloads(detail,"forecast").filter(row=>Number.isFinite(Number(row.expected_return)));if(forecasts.length){const longest=forecasts.slice().sort((a,b)=>Number(a.forecast_horizon_months)-Number(b.forecast_horizon_months)).at(-1);if(label)label.textContent="Forecast return";strong.textContent=fmtPct(Number(longest.expected_return)*100);strong.title=`${fmtNumber(longest.forecast_horizon_months,0)}-month governed expected return`;target.dataset.evidenceSource="forecast";return}if(label)label.textContent="Governed return";strong.textContent="Unavailable";strong.title="No governed return forecast is available for this asset; UIP does not infer one.";target.dataset.evidenceSource="unavailable";}
function setCardPrice(card,detail){const value=currentPrice(detail);if(!value)return;let target=card.querySelector(".metals-price-kpi");if(!target){const grid=card.querySelector(".metals-kpis");if(!grid)return;target=document.createElement("div");target.className="metals-kpi metals-price-kpi";target.innerHTML="<span>Current price</span><strong></strong>";grid.appendChild(target)}const strong=target.querySelector("strong");if(strong){strong.textContent=fmtMoney(value.current_price_usd);strong.title=`Observed ${value.observation_date||"date unavailable"} · certified unadjusted close authority`;}target.dataset.evidenceSource="metals_current_price";}
function setCommodityCardState(card,detail){if(!isCommodityDetail(detail))return false;card.classList.add("metals-card-commodity");const drawdown=findKpi(card,"Current drawdown");if(drawdown){const label=drawdown.querySelector("span"),strong=drawdown.querySelector("strong");if(label)label.textContent="Vehicle tactical";if(strong)strong.textContent="N/A";drawdown.dataset.evidenceSource="not_applicable";}const momentum=card.querySelector(".metals-momentum");if(momentum)momentum.outerHTML=`<div class="metals-card-na"><strong>Vehicle-level tactical only</strong><span>Commodity thesis records do not receive vehicle momentum or drawdown metrics.</span></div>`;const track=card.querySelector(".metals-regime-track");const trackContainer=track?.parentElement;if(trackContainer)trackContainer.outerHTML=`<div class="metals-na-callout"><strong>Tactical overlay not applicable</strong><span>Use commodity forecast and regime evidence in Research.</span></div>`;const mini=card.querySelector(".metals-tactical-mini");if(mini)mini.innerHTML="<span>Tactical context</span><strong>Not applicable</strong><span>Vehicle-level policy only</span>";return true;}
function setVehicleCardState(card,detail){const tactical=firstTactical(detail);if(!tactical)return;const mini=card.querySelector(".metals-tactical-mini");if(tactical.tactical_state==="NO_TACTICAL_OVERLAY"){card.classList.add("metals-card-no-overlay");if(mini)mini.innerHTML=`<span>Current tactical state</span><strong>No current overlay</strong><span>${escapeHtml(clean(tactical.candidate_regime??"Neutral or uncertain"))}</span>`;const track=card.querySelector(".metals-regime-track");if(track){const container=track.parentElement;if(container&&!container.querySelector(".metals-overlay-badge")){container.insertAdjacentHTML("afterbegin",'<div class="metals-overlay-badge neutral">No current tactical overlay</div>');}}}}
async function enrichCard(card){if(card.dataset.metalsEvidenceEnriched==="1")return;const button=card.querySelector(".rec-metals-detail[data-asset-id]");const assetId=button?.dataset?.assetId;if(!assetId)return;card.dataset.metalsEvidenceEnriched="pending";try{const detail=await detailRequest(assetId);if(detail){setCardForecast(card,detail);setCardPrice(card,detail);if(!setCommodityCardState(card,detail))setVehicleCardState(card,detail)}card.dataset.metalsEvidenceEnriched="1";}catch(_error){card.dataset.metalsEvidenceEnriched="0";}}
function enrichVisibleCards(){document.querySelectorAll(".metals-card").forEach(card=>{void enrichCard(card)})}
function chartMarkup(detail){const values=priceHistory(detail).filter(row=>Number.isFinite(Number(row.close_usd))&&row.observation_date);if(values.length<2)return "";const stride=Math.max(1,Math.ceil(values.length/180));const sampled=values.filter((_row,index)=>index%stride===0||index===values.length-1);const prices=sampled.map(row=>Number(row.close_usd));const low=Math.min(...prices),high=Math.max(...prices),span=high-low||1;const points=prices.map((value,index)=>`${(index/(prices.length-1))*1000},${190-((value-low)/span)*160}`).join(" ");const first=values[0],last=values[values.length-1];return `<article class="metals-panel metals-price-history-panel" data-evidence-source="metals_price_history"><h4>Historical market price</h4><p class="metals-panel-sub">Certified vehicle history · UNADJUSTED_CLOSE · ${escapeHtml(first.observation_date)} through ${escapeHtml(last.observation_date)} · ${values.length} observations.</p><div class="metals-price-chart-frame"><svg class="metals-price-chart" viewBox="0 0 1000 210" preserveAspectRatio="none"><polyline points="${points}"></polyline></svg></div><div class="metals-tactical-metrics metals-price-history-metrics"><div><span>Start</span><strong>${fmtMoney(first.close_usd)}</strong></div><div><span>Latest</span><strong>${fmtMoney(last.close_usd)}</strong></div><div><span>Period low</span><strong>${fmtMoney(low)}</strong></div><div><span>Period high</span><strong>${fmtMoney(high)}</strong></div></div></article>`}
function addHeroMetric(container,label,value,title=""){const node=document.createElement("div");node.className="metals-hero-metric";node.innerHTML=`<span>${escapeHtml(label)}</span><strong title="${escapeHtml(title)}">${escapeHtml(value)}</strong>`;container.appendChild(node);return node}
function enhanceCommodityHero(detail,side){const forecastRows=payloads(detail,"forecast").filter(row=>Number.isFinite(Number(row.expected_return)));const horizon=findKpi(side,"Forecast horizon");const expected=findKpi(side,"Expected return")||findKpi(side,"Standard forecast");const regime=findKpi(side,"Current regime");if(forecastRows.length){const longest=forecastRows.slice().sort((a,b)=>Number(a.forecast_horizon_months)-Number(b.forecast_horizon_months)).at(-1);if(horizon?.querySelector("strong"))horizon.querySelector("strong").textContent=`${fmtNumber(longest.forecast_horizon_months,0)} mo`;if(expected?.querySelector("strong"))expected.querySelector("strong").textContent=fmtPct(Number(longest.expected_return)*100);}else{if(horizon?.querySelector("strong"))horizon.querySelector("strong").textContent="N/A";if(expected){const label=expected.querySelector("span"),strong=expected.querySelector("strong");if(label)label.textContent="Standard forecast";if(strong)strong.textContent="Unavailable";}}
if(regime){const label=regime.querySelector("span"),strong=regime.querySelector("strong");if(label)label.textContent="Vehicle tactical";if(strong)strong.textContent="N/A";}const chips=[...document.querySelectorAll(".metals-hero .rec-chip")];const tacticalChip=chips.find(node=>node.textContent?.trim().startsWith("Tactical state"));if(tacticalChip)tacticalChip.textContent="Tactical: N/A · vehicle-level only";const kpis=document.querySelector(".metals-detail-kpis");if(kpis){kpis.classList.add("metals-commodity-context");kpis.innerHTML='<article class="metals-na-wide"><span>Vehicle-level tactical context</span><strong>Not applicable to commodity thesis</strong><small>Commodity research uses forecast, model-component, and regime evidence instead.</small></article>';}}
function enhanceHero(detail){const hero=document.querySelector(".metals-hero");if(!hero||hero.dataset.decisionUtilityEnhanced==="1")return;const side=hero.querySelector(".metals-hero-side");if(!side)return;if(isCommodityDetail(detail)){enhanceCommodityHero(detail,side);hero.dataset.decisionUtilityEnhanced="1";return}const price=currentPrice(detail);const best=bestUncertainty(detail);if(price){addHeroMetric(side,"Current price",fmtMoney(price.current_price_usd),"Certified vehicle current price");addHeroMetric(side,"Price as of",String(price.observation_date||"—"),"Certified market observation date");}const horizon=findKpi(side,"Forecast horizon");const expected=findKpi(side,"Expected return");if(best){if(horizon?.querySelector("strong"))horizon.querySelector("strong").textContent=`${fmtNumber(best.horizon_months,0)} mo`;if(expected){const label=expected.querySelector("span"),strong=expected.querySelector("strong");if(label)label.textContent="Raw expected return";if(strong)strong.textContent=fmtPct(Number(best.raw_expected_return)*100);}addHeroMetric(side,"Adjusted return",fmtPct(Number(best.adjusted_expected_return)*100),"Raw expected return less certified uncertainty and downside penalties");}hero.dataset.decisionUtilityEnhanced="1";}
function enhanceForecastPanel(detail){const panels=[...document.querySelectorAll("article.metals-panel")];const panel=panels.find(node=>node.querySelector("h4")?.textContent?.trim()==="Forecast & model evidence");if(!panel)return;const uncertainty=uncertaintyRows(detail);const models=modelComponents(detail);const assetId=detailAssetId(detail);const empty=panel.querySelector(".empty");if(uncertainty.length){if(empty)empty.remove();if(!panel.querySelector(".metals-forecast-return-context"))panel.insertAdjacentHTML("beforeend",uncertaintyTable(detail));panel.dataset.evidenceSource="metals_uncertainty_adjusted";return}if(models.length){if(empty){empty.textContent="Certified commodity model-component and expected-return evidence is available in Supporting Context. Price-point and forecast bounds are not populated.";empty.dataset.evidenceSource="metals_model_component";}return}if(assetId==="metals:commodity:uranium"&&empty){empty.textContent="Standard commodity forecast unavailable. UIP does not infer a Uranium forecast from URA or URNM vehicle evidence.";empty.dataset.evidenceSource="unavailable";}}
function enhanceRecommendationPanel(detail){const panels=[...document.querySelectorAll("article.metals-panel")];const panel=panels.find(node=>node.querySelector("h4")?.textContent?.trim()==="Why this recommendation");const change=recommendationChange(detail);if(!panel||!change?.explanation)return;const narrative=panel.querySelector(".rec-narrative");if(!narrative)return;const blocks=[...narrative.children];const rationale=blocks.find(node=>node.querySelector("span")?.textContent?.trim()==="Rationale");if(!rationale)return;const paragraph=rationale.querySelector("p");if(paragraph){paragraph.textContent=change.explanation;rationale.dataset.evidenceSource="metals_recommendation_change";if(!rationale.querySelector(".metals-secondary-copy"))rationale.insertAdjacentHTML("beforeend",'<small class="metals-secondary-copy">Full investment-thesis narrative is not populated in the current recommendation authority.</small>');}}
function enhancePriceHistory(detail){const markup=chartMarkup(detail);if(!markup)return;const panels=[...document.querySelectorAll("article.metals-panel")];if(panels.some(node=>node.classList.contains("metals-price-history-panel")))return;const momentum=panels.find(node=>node.querySelector("h4")?.textContent?.trim()==="Momentum & trend context");if(momentum)momentum.insertAdjacentHTML("afterend",markup);}
function enhanceResearchDetail(detail){if(!document.querySelector(".metals-hero")){pendingDetail=detail;return}enhanceHero(detail);enhanceForecastPanel(detail);enhanceRecommendationPanel(detail);enhancePriceHistory(detail);pendingDetail=null;}
const observer=new MutationObserver(()=>{enrichVisibleCards();if(pendingDetail)enhanceResearchDetail(pendingDetail)});
function startEnrichment(){if(!document.body)return;observer.observe(document.body,{childList:true,subtree:true});enrichVisibleCards();if(pendingDetail)enhanceResearchDetail(pendingDetail);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",startEnrichment,{once:true});else startEnrichment();
window.UIPMetalsTactical={RECORD_TYPE,DOMAIN,NO_OVERLAY_COPY,UNRESOLVED_COPY,COMMODITY_TACTICAL_COPY,firstTactical,tacticalViewModel,uncertaintyRows,bestUncertainty,recommendationChange,modelComponents,regimeProbabilities,currentPrice,priceHistory,renderTacticalPanel,enrichVisibleCards,enhanceResearchDetail};
})();
