(()=>{
"use strict";
const RECORD_TYPE="tactical_state";
const DOMAIN="metals";
const NO_OVERLAY_COPY="No tactical overlay means the frozen directional regime conditions are not currently satisfied; it is not a negative long-term thesis, sell signal, zero expected return, or allocation instruction.";
function clean(value){return String(value??"").replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase())}
function fmtPct(value){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:String(value)}
function firstTactical(detail){const rows=Array.isArray(detail?.records?.[RECORD_TYPE])?detail.records[RECORD_TYPE]:[];return rows.length?rows[0].payload||null:null}
function tacticalLabel(payload){if(!payload)return "Tactical state unavailable";if(payload.tactical_state==="TACTICAL_SUPPORTIVE")return "Tactical supportive";if(payload.tactical_state==="TACTICAL_DEFENSIVE")return "Tactical defensive";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return "No tactical overlay";return "Tactical state unavailable"}
function tacticalExplanation(payload){if(!payload)return "No certified tactical-state record is available for this asset.";if(payload.is_reference_control===true)return "Reference/control vehicle; not an opportunity recommendation.";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return NO_OVERLAY_COPY;return `Current bounded tactical interpretation: ${clean(payload.tactical_state)}. This does not replace the certified long-term recommendation, forecast, risk evidence, or execution controls.`}
function tacticalViewModel(detail){const payload=firstTactical(detail);return {recordType:RECORD_TYPE,domain:DOMAIN,label:tacticalLabel(payload),explanation:tacticalExplanation(payload),asOf:payload?.as_of_date??null,regime:payload?.candidate_regime??null,stateReason:payload?.state_reason??null,isReferenceControl:payload?.is_reference_control===true,available:payload?.state_available===true,return1m:payload?.return_1m_pct??null,return3m:payload?.return_3m_pct??null,return6m:payload?.return_6m_pct??null,distanceMa50:payload?.distance_ma50_pct??null,distanceMa200:payload?.distance_ma200_pct??null,drawdown:payload?.current_drawdown_pct??null,volatility3m:payload?.realized_volatility_3m_pct??null};}
function renderTacticalPanel(detail){const vm=tacticalViewModel(detail);const asOf=vm.asOf?`<span>As of ${vm.asOf}</span>`:"<span>As-of date unavailable</span>";const regime=vm.regime?`<span>Regime: ${clean(vm.regime)}</span>`:"";const reason=vm.stateReason?`<small>${clean(vm.stateReason)}</small>`:"";return `<aside class="rec-tactical-panel metals-tactical-rich" data-record-type="${RECORD_TYPE}"><span class="eyebrow">TACTICAL CONTEXT</span><h4>${vm.label}</h4><p>${vm.explanation}</p><div class="rec-tactical-meta">${asOf}${regime}</div><div class="metals-tactical-metrics"><div><span>1M momentum</span><strong>${fmtPct(vm.return1m)}</strong></div><div><span>3M momentum</span><strong>${fmtPct(vm.return3m)}</strong></div><div><span>6M momentum</span><strong>${fmtPct(vm.return6m)}</strong></div><div><span>Current drawdown</span><strong>${fmtPct(vm.drawdown)}</strong></div><div><span>vs MA50</span><strong>${fmtPct(vm.distanceMa50)}</strong></div><div><span>vs MA200</span><strong>${fmtPct(vm.distanceMa200)}</strong></div><div><span>3M volatility</span><strong>${fmtPct(vm.volatility3m)}</strong></div></div>${reason}</aside>`;}
window.UIPMetalsTactical={RECORD_TYPE,DOMAIN,NO_OVERLAY_COPY,firstTactical,tacticalViewModel,renderTacticalPanel};
})();
