(()=>{
"use strict";
const RECORD_TYPE="tactical_state";
const DOMAIN="metals";
const NO_OVERLAY_COPY="No tactical overlay means the frozen directional regime conditions are not currently satisfied; it is not a negative long-term thesis, sell signal, zero expected return, or allocation instruction.";
const UNRESOLVED_COPY="Unsupported fields remain unavailable rather than being synthesized from semantically different evidence.";
function clean(value){return String(value??"").replaceAll("_"," ").toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase())}
function fmtPct(value){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:String(value)}
function fmtNumber(value,digits=2){if(value===null||value===undefined||value==="")return "—";const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):String(value)}
function rows(detail,type){return Array.isArray(detail?.records?.[type])?detail.records[type]:[]}
function payloads(detail,type){return rows(detail,type).map(record=>record.payload||{})}
function firstTactical(detail){const tactical=rows(detail,RECORD_TYPE);return tactical.length?tactical[0].payload||null:null}
function uncertaintyRows(detail){return payloads(detail,"metals_uncertainty_adjusted").slice().sort((a,b)=>Number(a.horizon_months)-Number(b.horizon_months))}
function bestUncertainty(detail){const values=uncertaintyRows(detail);return values.length?values[values.length-1]:null}
function recommendationChange(detail){return payloads(detail,"metals_recommendation_change")[0]||null}
function modelComponents(detail){return payloads(detail,"metals_model_component").slice().sort((a,b)=>Number(a.horizon_months)-Number(b.horizon_months)||String(a.model_name||"").localeCompare(String(b.model_name||"")))}
function regimeProbabilities(detail){return payloads(detail,"metals_regime_probability").slice().sort((a,b)=>Number(b.probability)-Number(a.probability))}
function isCommodityDetail(detail){return !firstTactical(detail)&&modelComponents(detail).length>0}
function tacticalLabel(payload,commodity=false){if(commodity)return "Vehicle-level tactical context not applicable";if(!payload)return "Tactical state unavailable";if(payload.tactical_state==="TACTICAL_SUPPORTIVE")return "Tactical supportive";if(payload.tactical_state==="TACTICAL_DEFENSIVE")return "Tactical defensive";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return "No tactical overlay";return "Tactical state unavailable"}
function tacticalExplanation(payload,commodity=false){if(commodity)return "This commodity research record is the long-term metal thesis. The certified V3 tactical policy is defined on investable Metals vehicles, so no commodity tactical state is synthesized here.";if(!payload)return "No certified vehicle tactical-state record is available for this asset.";if(payload.is_reference_control===true)return "Reference/control vehicle; not an opportunity recommendation.";if(payload.tactical_state==="NO_TACTICAL_OVERLAY")return NO_OVERLAY_COPY;return `Current bounded tactical interpretation: ${clean(payload.tactical_state)}. This does not replace the certified long-term recommendation, forecast, risk evidence, or execution controls.`}
function tacticalViewModel(detail){const payload=firstTactical(detail);const commodity=isCommodityDetail(detail);return {recordType:RECORD_TYPE,domain:DOMAIN,label:tacticalLabel(payload,commodity),explanation:tacticalExplanation(payload,commodity),commodity,asOf:payload?.as_of_date??null,regime:payload?.candidate_regime??null,stateReason:payload?.state_reason??null,isReferenceControl:payload?.is_reference_control===true,available:payload?.state_available===true,return1m:payload?.return_1m_pct??null,return3m:payload?.return_3m_pct??null,return6m:payload?.return_6m_pct??null,distanceMa50:payload?.distance_ma50_pct??null,distanceMa200:payload?.distance_ma200_pct??null,drawdown:payload?.current_drawdown_pct??null,volatility3m:payload?.realized_volatility_3m_pct??null};}
function uncertaintyTable(detail){const values=uncertaintyRows(detail);if(!values.length)return "";return `<section class="metals-evidence-block"><h5>Forecast return context</h5><p class="governance-note">Raw and uncertainty-adjusted expected returns are certified vehicle evidence. Penalties are shown as model adjustments, not forecast bounds or generic risk scores.</p><div class="rec-detail-table"><table><thead><tr><th>Horizon</th><th>Raw expected return</th><th>Adjusted expected return</th><th>Uncertainty penalty</th><th>Downside penalty</th></tr></thead><tbody>${values.map(row=>`<tr><td>${fmtNumber(row.horizon_months,0)} mo</td><td>${fmtPct(Number(row.raw_expected_return)*100)}</td><td>${fmtPct(Number(row.adjusted_expected_return)*100)}</td><td>${fmtPct(Number(row.uncertainty_penalty)*100)}</td><td>${fmtPct(Number(row.downside_penalty)*100)}</td></tr>`).join("")}</tbody></table></div></section>`}
function recommendationChangeBlock(detail){const value=recommendationChange(detail);if(!value)return "";return `<section class="metals-evidence-block"><h5>Recommendation evidence</h5><div class="metals-tactical-metrics"><div><span>Previous action</span><strong>${clean(value.previous_action??"unavailable")}</strong></div><div><span>Current action</span><strong>${clean(value.current_action??"unavailable")}</strong></div><div><span>Previous confidence</span><strong>${fmtNumber(value.previous_confidence)}</strong></div><div><span>Current confidence</span><strong>${fmtNumber(value.current_confidence)}</strong></div></div><p class="governance-note">${value.explanation??"No recommendation-change explanation is populated."}</p></section>`}
function commodityModelBlock(detail){const models=modelComponents(detail);if(!models.length)return "";return `<section class="metals-evidence-block"><h5>Commodity model components</h5><p class="governance-note">Certified component forecasts are shown with their source model weights. They are not synthesized into unsupported price bounds.</p><div class="rec-detail-table"><table><thead><tr><th>Horizon</th><th>Model</th><th>Model forecast</th><th>Weight</th></tr></thead><tbody>${models.map(row=>`<tr><td>${fmtNumber(row.horizon_months,0)} mo</td><td>${clean(row.model_name??"unavailable")}</td><td>${fmtNumber(row.model_forecast,4)}</td><td>${fmtPct(Number(row.model_weight)*100)}</td></tr>`).join("")}</tbody></table></div></section>`}
function commodityRegimeBlock(detail){const regimes=regimeProbabilities(detail);if(!regimes.length)return "";return `<section class="metals-evidence-block"><h5>Commodity regime probabilities</h5><div class="metals-tactical-metrics">${regimes.map(row=>`<div><span>${clean(row.regime??"regime")}</span><strong>${fmtPct(Number(row.probability)*100)}</strong></div>`).join("")}</div><p class="governance-note">These are long-term forecast-regime probabilities, not the vehicle tactical classifier.</p></section>`}
function renderTacticalPanel(detail){const vm=tacticalViewModel(detail);const asOf=vm.asOf?`<span>As of ${vm.asOf}</span>`:vm.commodity?"<span>Vehicle tactical as-of: not applicable</span>":"<span>As-of date unavailable</span>";const regime=vm.regime?`<span>Regime: ${clean(vm.regime)}</span>`:"";const reason=vm.stateReason?`<small>${clean(vm.stateReason)}</small>`:"";const metrics=vm.commodity?"":`<div class="metals-tactical-metrics"><div><span>1M momentum</span><strong>${fmtPct(vm.return1m)}</strong></div><div><span>3M momentum</span><strong>${fmtPct(vm.return3m)}</strong></div><div><span>6M momentum</span><strong>${fmtPct(vm.return6m)}</strong></div><div><span>Current drawdown</span><strong>${fmtPct(vm.drawdown)}</strong></div><div><span>vs MA50</span><strong>${fmtPct(vm.distanceMa50)}</strong></div><div><span>vs MA200</span><strong>${fmtPct(vm.distanceMa200)}</strong></div><div><span>3M volatility</span><strong>${fmtPct(vm.volatility3m)}</strong></div></div>`;const evidence=vm.commodity?`${commodityRegimeBlock(detail)}${commodityModelBlock(detail)}`:`${uncertaintyTable(detail)}${recommendationChangeBlock(detail)}`;return `<aside class="rec-tactical-panel metals-tactical-rich" data-record-type="${RECORD_TYPE}"><span class="eyebrow">TACTICAL & SUPPORTING CONTEXT</span><h4>${vm.label}</h4><p>${vm.explanation}</p><div class="rec-tactical-meta">${asOf}${regime}</div>${metrics}${reason}${evidence}<p class="governance-note">${UNRESOLVED_COPY}</p></aside>`;}
async function detailRequest(assetId){const key=sessionStorage.getItem("uiip-dashboard-key")||"";if(!key)return null;const response=await fetch(`/v1/presentation/assets/${encodeURIComponent(DOMAIN)}/${encodeURIComponent(assetId)}`,{headers:{"X-API-Key":key,"Accept":"application/json"}});if(!response.ok)return null;return response.json()}
function setCardForecast(card,detail){const best=bestUncertainty(detail);if(!best)return;const target=[...card.querySelectorAll(".metals-kpi")].find(node=>node.querySelector("span")?.textContent?.trim()==="Forecast return");if(!target)return;const strong=target.querySelector("strong");if(!strong)return;strong.textContent=fmtPct(Number(best.adjusted_expected_return)*100);strong.title=`${fmtNumber(best.horizon_months,0)}-month uncertainty-adjusted expected return`;target.dataset.evidenceSource="metals_uncertainty_adjusted";}
async function enrichCard(card){if(card.dataset.metalsEvidenceEnriched==="1")return;const button=card.querySelector(".rec-metals-detail[data-asset-id]");const assetId=button?.dataset?.assetId;if(!assetId)return;card.dataset.metalsEvidenceEnriched="pending";try{const detail=await detailRequest(assetId);if(detail)setCardForecast(card,detail);card.dataset.metalsEvidenceEnriched="1";}catch(_error){card.dataset.metalsEvidenceEnriched="0";}}
function enrichVisibleCards(){document.querySelectorAll(".metals-card").forEach(card=>{void enrichCard(card)})}
const observer=new MutationObserver(()=>enrichVisibleCards());
function startEnrichment(){if(!document.body)return;observer.observe(document.body,{childList:true,subtree:true});enrichVisibleCards();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",startEnrichment,{once:true});else startEnrichment();
window.UIPMetalsTactical={RECORD_TYPE,DOMAIN,NO_OVERLAY_COPY,UNRESOLVED_COPY,firstTactical,tacticalViewModel,uncertaintyRows,bestUncertainty,recommendationChange,modelComponents,regimeProbabilities,renderTacticalPanel,enrichVisibleCards};
})();
