ASSET_POLICIES={
"crypto":["ONE_DAY","ONE_WEEK","TWO_WEEKS","ONE_MONTH","THREE_MONTHS","SIX_MONTHS","ONE_YEAR","TWO_YEARS","THREE_YEARS","FIVE_YEARS"],
"stocks":["ONE_DAY","ONE_WEEK","ONE_MONTH","THREE_MONTHS","SIX_MONTHS","ONE_YEAR","THREE_YEARS","FIVE_YEARS"],
"housing":["SIX_MONTHS","ONE_YEAR","TWO_YEARS","THREE_YEARS","FIVE_YEARS","TEN_YEARS"],
"metals":["ONE_WEEK","ONE_MONTH","THREE_MONTHS","SIX_MONTHS","ONE_YEAR","THREE_YEARS","FIVE_YEARS"],
"mtg":["ONE_YEAR","THREE_YEARS","FIVE_YEARS","TEN_YEARS"],
"macro":["ONE_MONTH","THREE_MONTHS","SIX_MONTHS","ONE_YEAR"]
}
