class ForecastError(Exception): ...
class ForecastValidationError(ForecastError): ...
class ForecastModelError(ForecastError): ...
class ForecastRegistryError(ForecastError): ...
class ForecastSerializationError(ForecastError): ...
