from enum import Enum
class ForecastStatus(str, Enum):
    CREATED="CREATED"
    QUEUED="QUEUED"
    RUNNING="RUNNING"
    COMPLETED="COMPLETED"
    FAILED="FAILED"
    INVALID="INVALID"
    CALIBRATED="CALIBRATED"
    CERTIFIED="CERTIFIED"
    ARCHIVED="ARCHIVED"
