"""Universal investment decision intelligence."""

from .allocation import (
    AllocationConfigurationError,
    AllocationInputError,
    AllocationProfile,
    AllocationRecommendationError,
    AllocationResult,
    UniversalAllocationEngine,
)
from .classification import (
    ActionClassificationError,
    ActionClassificationResult,
    ClassificationInputError,
    UniversalActionClassificationEngine,
)
from .confidence import (
    DEFAULT_CONFIDENCE_WEIGHTS,
    ConfidenceAggregationError,
    ConfidenceBand,
    ConfidenceConfigurationError,
    ConfidenceInputError,
    ConfidenceProfile,
    ConfidenceResult,
    UniversalConfidenceAggregationEngine,
)
from .constraints import (
    ConstraintCheck,
    ConstraintEvaluationError,
    ConstraintEvaluationResult,
    ConstraintInputError,
    ConstraintStatus,
    UniversalConstraintEngine,
)
from .contracts import (
    DecisionAction,
    DecisionContext,
    DecisionContractError,
    DecisionEvidence,
    DecisionInput,
    DecisionPolicy,
    DecisionPolicyError,
    DecisionResult,
    DecisionScore,
    DecisionStatus,
    DecisionValidationError,
    EligibilityStatus,
)
from .eligibility import (
    EligibilityCheck,
    EligibilityResult,
    UniversalEligibilityEngine,
)
from .explanation import (
    DecisionExplanation,
    DecisionExplanationError,
    ExplanationConfigurationError,
    ExplanationInputError,
    ExplanationProfile,
    UniversalDecisionExplanationEngine,
)
from .orchestration import (
    DecisionOrchestrationError,
    DecisionOrchestrationResult,
    OrchestrationConfigurationError,
    OrchestrationConsistencyError,
    OrchestrationInputError,
    OrchestrationProfile,
    UniversalDecisionOrchestrator,
)
from .scoring import (
    DEFAULT_COMPONENT_WEIGHTS,
    DecisionScoringError,
    DecisionScoringProfile,
    IneligibleScoringError,
    ScoringConfigurationError,
    UniversalDecisionScoringEngine,
)

__all__ = [
    "ActionClassificationError",
    "ActionClassificationResult",
    "AllocationConfigurationError",
    "AllocationInputError",
    "AllocationProfile",
    "AllocationRecommendationError",
    "AllocationResult",
    "ClassificationInputError",
    "ConfidenceAggregationError",
    "ConfidenceBand",
    "ConfidenceConfigurationError",
    "ConfidenceInputError",
    "ConfidenceProfile",
    "ConfidenceResult",
    "ConstraintCheck",
    "ConstraintEvaluationError",
    "ConstraintEvaluationResult",
    "ConstraintInputError",
    "ConstraintStatus",
    "DEFAULT_COMPONENT_WEIGHTS",
    "DEFAULT_CONFIDENCE_WEIGHTS",
    "DecisionAction",
    "DecisionContext",
    "DecisionContractError",
    "DecisionEvidence",
    "DecisionExplanation",
    "DecisionExplanationError",
    "DecisionInput",
    "DecisionPolicy",
    "DecisionPolicyError",
    "DecisionOrchestrationError",
    "DecisionOrchestrationResult",
    "DecisionResult",
    "DecisionScore",
    "DecisionScoringError",
    "DecisionScoringProfile",
    "DecisionStatus",
    "DecisionValidationError",
    "EligibilityCheck",
    "EligibilityResult",
    "EligibilityStatus",
    "ExplanationConfigurationError",
    "ExplanationInputError",
    "ExplanationProfile",
    "IneligibleScoringError",
    "OrchestrationConfigurationError",
    "OrchestrationConsistencyError",
    "OrchestrationInputError",
    "OrchestrationProfile",
    "ScoringConfigurationError",
    "UniversalActionClassificationEngine",
    "UniversalAllocationEngine",
    "UniversalConfidenceAggregationEngine",
    "UniversalConstraintEngine",
    "UniversalDecisionExplanationEngine",
    "UniversalDecisionScoringEngine",
    "UniversalDecisionOrchestrator",
    "UniversalEligibilityEngine",
]

